lang: en_us
debug: false
logChat: true
sleepPercent: 50
afkTimeout: 180
nickMaxLength: 20
discord:
  verificationEnabled: true
  codeLength: 4
  useWebhook: true
  webhookProxy: ""
  token: ""
  verificationChannel: ""
  chatChannel: ""
googleapikey: ""